weight = float(input("Enter your weight (kg): "))
height = float(input("Enter your height (m): "))
bmi = weight / (height ** 2)
print("\nWeight:", weight, "kg")
print("Height:", height, "m")
print("BMI:", round(bmi, 2))